### ISSUE TITLE
Lists fail to parse if first line is a comment

### ISSUE THREAD

**Issue by michael-projectx** [miker2/flexi_config_reader#113]
The following won't parse properly:

```
foo = [
  # Comment
  "one",
  "two",
  "three"
]
```

**Comment by miker2** [comment]
Comments should be allowed within lists in general. PEGTL provides a rule for lists with padded separators. 

We may want our own custom rule so that comments can come after a comma, but not before

Something like:

list<R, pad<",", blank, COMMENT>>

**Comment by miker2** [comment]
See also issue #114

**Comment by miker2** [comment]
See also issue #125

**Comment by michael-projectx** [comment]
Completed by PR #127
