### ISSUE TITLE
Fix 'relative_include' error messages when the same file is included more than once

### ISSUE THREAD

**Issue by michael-projectx** [miker2/flexi_config_reader#132]
It appears that if we have a file like this:

```
include_relative ../foo.cfg
include_relative ../bar.cfg
```

and `foo.cfg` look like this:

```
include_relative bar.cfg

struct foo {
  ...
}
```

Then the resulting error message is not as helpful as it could be.

Needs investigation.

**Comment by jayv** [comment]
This is now supported with `include [once]`
